### ISSUE TITLE
What is the dataset you have used...

### ISSUE THREAD

**Issue by vdsprakash** [idearibosome/tf-perceptual-eusr#1]

**Comment by idearibosome** [comment]
We trained our model with the DIV2K dataset, which was used in the NTIRE challenge. https://data.vision.ee.ethz.ch/cvl/DIV2K/
Our model supports multiple upscaling factors in the same model (e.g., x2, x4, x8), however, the original dataset does not provide training images downscaled by a factor of 8. Therefore, you have to manually downscale the high resolution (HR) images.

**Comment by idearibosome** [comment]
Updates: We added a helper script to obtain downscaled images (```train/misc/downscale_generator_matlab.m```). Just download the high resolution (HR) images from the official DIV2K dataset website and generate downscaled images by the provided script. Detailed instruction is also provided in ```train/README.md```.
