### ISSUE TITLE
looking for aesthetic and subjective qualitative score loss  ?

### ISSUE THREAD

**Issue by ranjiewwen** [idearibosome/tf-perceptual-eusr#2]
- i am interesting about this work. beause of you add Qualitative score predictors.
- but i not found about this part in the code. looking for you complete training aesthetic and subjective qualitative score predictors and add loss to SR task. 
- by the way. i am trying this on another task.

**Comment by idearibosome** [comment]
Hi, thanks for your comment. :)

We are working on writing the score predictors as you mentioned.
At this moment, you can find out some code (i.e., training subjective score predictor) in [train-score-predictor](https://github.com/idearibosome/tf-perceptual-eusr/tree/train-score-predictor) branch. We will merge the branch into master when we finish the implementation.

**Comment by ranjiewwen** [comment]
@idearibosome thanks! look for the result .

**Comment by idearibosome** [comment]
@ranjiewwen Good news: the training code of aesthetic score predictor is added and the train-score-predictor branch is merged into the master branch.

**Comment by ranjiewwen** [comment]
> @ranjiewwen Good news: the training code of aesthetic score predictor is added and the train-score-predictor branch is merged into the master branch.

thanks, good!
