### ISSUE TITLE
Could you please provide the code of training the 4PP-EUSR model

### ISSUE THREAD

**Issue by lycutter** [idearibosome/tf-perceptual-eusr#4]
Hi, I am really interested in this work and thanks for your code. I wonder if you could release the  remaining code of training the 4PP-EUSR code as there are some details which are not mentioned in the paper.
Best Regards.

**Comment by idearibosome** [comment]
Hi, lycutter!

We updated this repository to fully support training our 4PP-EUSR model. Please check out https://github.com/idearibosome/tf-perceptual-eusr/tree/master/train for more information. :D

Also, please feel free to ask questions about the details that are not included in our paper.
Thanks!

**Comment by lycutter** [comment]
@idearibosome Thanks for your help.
